### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by chrisdmacrae**
Update the README to be easier to use

### CODE REVIEW

**Comment by envygeeks** [comment]
Next time please go through the maintainer before merging your documentation changes randomly.

**Comment by jpatters** [comment]
@envygeeks can you please undo this. I asked chris to make these changes.

**Comment by envygeeks** [comment]
I didn't revert it.

**Comment by jpatters** [comment]
Oh ok. Sorry. I misread the commit

**Pull request merged**
